namespace IDAProject.Web.Models.General.Enums
{
    public enum CostIncomeTypes
    {
        Transportation_cost = 1,
        Variable_cost_per_mile = 2,
        Vehicle_renting_cost = 3,
        Trailer_renting_cost = 4,
        Cargo_and_liability_insurance = 5,
        Physical_insurance = 6,
        Extra_Cargo_Insurance = 7,
        ELD = 8,
        Registration = 9,
        Maintenance_cost = 10,
        Fuel_cost = 11,
        IFTA = 12,
        Highway_cost = 13,
        Extra_vehicle_cost = 14,
        Extra_tour_cost = 15,
        Fuel_card_cost = 16,
        Mileage_fee = 17,
        ESCROW = 18,
        Ticket_cost = 19,
        Loans = 20,
        Reimbursements = 21,
        Cost_refundations = 22,
        Bonuses = 23,
        Waiting_bonuses = 24,
        Stops_bonuses = 25,
        Inspection_bonuses = 26,
        Inspection_credits = 27,
        Fuel = 28,
        Tour_income = 29,
        Extra_tour_costs = 30,
        Non_drivers_salaries = 31,
        Office_rents = 32,
        Office_maintenance = 33,
        Overheads = 34,
        Representation_costs = 35,
        Amortization = 36,
        Licences_software_la_and_other_services = 37,
        Equipment_costs = 38,
        Oportunity_cost_of_investment = 39
    }
}
